#ifndef _OS_MMAN_H_
#define _OS_MMAN_H_


#include "../include/pipe/p_config.h"
#include "../include/pipe/p_compiler.h"

#if defined(PIPE_OS_UNIX)
#  include <sys/mman.h>
#else
#  error Unsupported OS
#endif

#ifdef  __cplusplus
extern "C" {
#endif


#if defined(PIPE_OS_ANDROID) && !defined(__LP64__)
/* 32-bit needs mmap64 for 64-bit offsets */
#  define os_mmap(addr, length, prot, flags, fd, offset) \
             mmap64(addr, length, prot, flags, fd, offset)

#  define os_munmap(addr, length) \
             munmap(addr, length)

#else
/* assume large file support exists */
#  define os_mmap(addr, length, prot, flags, fd, offset) \
             mmap(addr, length, prot, flags, fd, offset)

static inline int os_munmap(void *addr, size_t length)
{
    /* Copied from configure code generated by AC_SYS_LARGEFILE */
#define LARGE_OFF_T ((((off_t) 1 << 31) << 31) - 1 + \
                     (((off_t) 1 << 31) << 31))
    STATIC_ASSERT(LARGE_OFF_T % 2147483629 == 721 &&
                  LARGE_OFF_T % 2147483647 == 1);
#undef LARGE_OFF_T

    return munmap(addr, length);
}
#endif


#ifdef	__cplusplus
}
#endif

#endif /* _OS_MMAN_H_ */
