#define VERSION '0.8.1'
#define _GNU_SOURCE 1
#define VIRGL_RENDERER_UNSTABLE_APIS 1
#define HAVE___BUILTIN_BSWAP32 1
#define HAVE___BUILTIN_BSWAP64 1
#define HAVE___BUILTIN_CLZ 1
#define HAVE___BUILTIN_CLZLL 1
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___BUILTIN_FFS 1
#define HAVE___BUILTIN_FFSLL 1
#define HAVE___BUILTIN_POPCOUNT 1
#define HAVE___BUILTIN_POPCOUNTLL 1
#define HAVE___BUILTIN_TYPES_COMPATIBLE_P 1
#define HAVE___BUILTIN_UNREACHABLE 1
#define HAVE_FUNC_ATTRIBUTE_CONST 1
#define HAVE_FUNC_ATTRIBUTE_FLATTEN 1
#define HAVE_FUNC_ATTRIBUTE_FORMAT 1
#define HAVE_FUNC_ATTRIBUTE_MALLOC 1
#define HAVE_FUNC_ATTRIBUTE_NORETURN 1
#define HAVE_FUNC_ATTRIBUTE_PACKED 1
#define HAVE_FUNC_ATTRIBUTE_PURE 1
#define HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL 1
#define HAVE_FUNC_ATTRIBUTE_UNUSED 1
#define HAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT 1
#define HAVE_FUNC_ATTRIBUTE_WEAK 1
#undef HAVE_STRTOK_R
#define HAVE_TIMESPEC_GET 1
#define HAVE_SYS_UIO_H 1
#define HAVE_PTHREAD 1
#define HAVE_PTHREAD_SETAFFINITY 1
#undef HAVE_EPOXY_EGL_H
#define HAVE_EPOXY_GLX_H 1
#define ENABLE_MINIGBM_ALLOCATION 1
#define ENABLE_VENUS 0
#define ENABLE_VENUS_VALIDATE 0
#define HAVE_FUNC_ATTRIBUTE_VISIBILITY 1
#define HAVE_EVENTFD_H 1
#define HAVE_DLFCN_H 1

#define ENABLE_TRACING TRACE_WITH_STDERR

#define UTIL_ARCH_LITTLE_ENDIAN 1
#define UTIL_ARCH_BIG_ENDIAN 0

#undef PIPE_ARCH_X86
#undef PIPE_ARCH_X86_64
#undef PIPE_ARCH_PPC
#undef PIPE_ARCH_PPC_64
#undef PIPE_ARCH_S390
#define PIPE_ARCH_ARM true
#undef PIPE_ARCH_AARCH64
